foundation/ontrack/config/routes.rb
Rails.application.routes.draw do
  root to: "projects#index"
  resources :projects do
  resources :tasks
end

end

foundation/ontrack/app/models/project.rb
class Project < ActiveRecord::Base
end

foundation/ontrack/app/models/task.rb
class Task < ActiveRecord::Base
end

foundation/ontrack/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

foundation/ontrack/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def index
		@projects = Project.all	
	end
	def show
		@project = Project.find(params[:id])
	end
	def new
		@project = Project.new
	end
	def create
		@project = Project.new(project_params)
		if @project.save
			flash[:notice] = "gut gespeichert ist halb gewonnen"
		redirect_to project_path(@project.id)	
		else
		render "new"	
	end
end
	def edit
		@project = Project.find(params[:id])
	end
	def update
		@project = Project.find(params[:id])
		
		if @project.update(project_params)
		redirect_to project_path(@project.id)
		else
			render "edit"
		end
	end
	def destroy
		@project = Project.find(params[:id])
		@project.destroy
		redirect_to projects_url
	end
	private
	def project_params
		params.require(:project).permit(:title, :description, :start_date)
	end
end

foundation/ontrack/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @task = @project.tasks
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @tasks = @project.task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = @project.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:project_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :discription, :start_date, :end_date, :project_id)
    end
end

foundation/ontrack/app/helpers/application_helper.rb
module ApplicationHelper
end

foundation/ontrack/app/helpers/projects_helper.rb
module ProjectsHelper
end

foundation/ontrack/app/helpers/tasks_helper.rb
module TasksHelper
end

foundation/ontrack/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

foundation/ontrack/app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

foundation/ontrack/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

foundation/ontrack/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ontrack" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Ontrack" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

foundation/ontrack/app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
	<div class="row">
		<div class=" medium-2 columns">
			<%= f.label :title %>
		</div>
		<div class=" medium-10 columns">
			<%= f.text_field :title %>
		</div>
	</div>
	<div class="row">
		<div class=" medium-2 columns">
			<%= f.label :description %>
		</div>
		<div class=" medium-10 columns">
			<%= f.text_area :description %>
		</div>
		</div>
	<div class="row">
		<div class=" medium-2 columns">
			<%= f.label :start_date %>
		</div>
		<div class=" medium-10 columns">
			<%= f.text_field :start_date %>
		</div>
		</div>

		<div class="row">
			<div class="medium-2 columns"><%= f.submit "Neues Projekt erstellen", class: "butten success" %></div>
			<div class="medium-10 columns">&nbsp;</div>
		</div>
<% end %>

foundation/ontrack/app/views/projects/edit.html.erb
<h1> Projekt: <% @project.title %> bearbeiten</h1>

<%= render "form" %>

foundation/ontrack/app/views/projects/index.html.erb
<h1>Projects</h1>
<p><%= link_to "Neues Projekt erstellen", new_project_path %></p>
<p>Zeige folgende <% @projects.size %> an:
	<table>
		<tr>
			<th>Name</th>
			<th>Beschreibung</th>
			<th>Start Datum</th>
		</tr>
		<% @projects.each do |project| %>
			<tr>
				<td><%= project.title %></td>
				<td><%= truncate(project.description, length: 25, seperator: ' ', omission: " ") %>
					<%= link_to "...", project_path(project.id) %>
				<td><%= project.start_date %></td>


				</td>
				<td><%= link_to "Show", project_path(project.id) %></td>
				<td><%= link_to "Edit", edit_project_path(project.id) %></td>
				<td><%= link_to "Delete", project_path(project.id), method: :delete, data: {confirm: "Sicher?"} %></td>
			</tr>
		<% end %>
	</table>
</p>

foundation/ontrack/app/views/projects/new.html.erb
<h1>Neues Projekt erstellen</h1>

<%= render "form" %>

foundation/ontrack/app/views/projects/show.html.erb
<h1><%= @project.title %></h1>

	<div class="panel">
		<div class="row">
		<div class=" medium-2 columns">
			Beschreibung
		</div>
		<div class=" medium-10 columns">
			<%= @project.description %>
		</div>
		</div>
		<div class="row">
		<div class=" medium-2 columns">
			Wo
		</div>
		<div class=" medium-10 columns">
			<%= @project.start_date %>
		</div>


<ul class="button-group even-3">
		<li><%= link_to "Back", projects_path, class: "button alert" %></li>

		<li><%= link_to "Vorhandene Tasks", project_tasks_path((@project.id)), class: "button alert" %></li>
		<li><%= link_to "Neuer Task", new_project_task_path((@project.id)), class: "button alert" %></li>


</ul>

foundation/ontrack/app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :discription %><br>
    <%= f.text_field :discription %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.number_field :project_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

foundation/ontrack/app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

foundation/ontrack/app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Discription</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.discription %></td>
        <td><%= task.start_date %></td>
        <td><%= task.end_date %></td>
        <td><%= task.project_id %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

foundation/ontrack/app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

foundation/ontrack/app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Discription:</strong>
  <%= @task.discription %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @task.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @task.end_date %>
</p>

<p>
  <strong>Project:</strong>
  <%= @task.project_id %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>